version: "3.9"

volumes:
  pg_data:
  web_media:

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python app/manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    volumes:
      - web_media:/project/app/media/
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


