# Generated by Django 4.1.6 on 2023-02-11 07:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to=store.services.models.get_photo_path_for_category)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(store.services.models.InstanceImage, models.Model),
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(auto_created=True, default=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('amount', models.PositiveIntegerField(default=100)),
                ('photo', models.ImageField(upload_to=store.services.models.get_photo_path_for_product)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_size', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=99)])),
                ('calories', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('proteins', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('fats', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('carbohydrates', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('packing_date', models.DateTimeField(default=datetime.datetime(2023, 2, 11, 3, 48, 58, 156613))),
                ('sell_before', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 48, 58, 156634))),
                ('min_temperature', models.SmallIntegerField(default=-5)),
                ('max_temperature', models.SmallIntegerField(default=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='store.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers_products', to='store.producer')),
            ],
            bases=(store.services.models.InstanceImage, models.Model),
        ),
    ]
