# Generated by Django 4.1.6 on 2023-02-08 11:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(auto_created=True, default=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=200)),
                ('amount', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_size', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=99)])),
                ('calories', models.PositiveSmallIntegerField(blank=True, help_text='per_100_grams', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('proteins', models.PositiveSmallIntegerField(blank=True, help_text='per_100_grams', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('fats', models.PositiveSmallIntegerField(blank=True, help_text='per_100_grams', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('carbohydrates', models.PositiveSmallIntegerField(blank=True, help_text='per_100_grams', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('packing_date', models.DateTimeField(default=datetime.datetime(2023, 2, 8, 7, 52, 57, 513452))),
                ('sell_before', models.DateTimeField(default=datetime.datetime(2023, 2, 15, 11, 52, 57, 513471))),
                ('min_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('max_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='store.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers_products', to='store.producer')),
            ],
        ),
    ]
