# Generated by Django 4.1.6 on 2023-02-18 06:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('photo', models.ImageField(upload_to=store.services.models.get_photo_path_for_category)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(store.services.models.InstanceImage, models.Model),
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(auto_created=True, default=True)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='volume/weight')),
                ('measure', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], max_length=5)),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('photo', models.ImageField(upload_to=store.services.models.get_photo_path_for_product)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_size', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=99)])),
                ('calories', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('proteins', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('fats', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('carbohydrates', models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('min_temperature', models.SmallIntegerField(default=-5)),
                ('max_temperature', models.SmallIntegerField(default=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producer')),
            ],
            options={
                'unique_together': {('name', 'weight', 'measure', 'producer')},
            },
            bases=(store.services.models.InstanceImage, models.Model),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('packing_date', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 2, 30, 51, 414864))),
                ('sell_before', models.DateTimeField(default=datetime.datetime(2023, 2, 25, 6, 30, 51, 414875))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Batches',
            },
        ),
    ]
