# Generated by Django 4.1.6 on 2023-02-24 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 0, 58, 21, 107819)),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 4, 58, 21, 107835)),
        ),
    ]
