# Generated by Django 4.1.6 on 2023-02-10 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='height',
            field=models.PositiveSmallIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='category',
            name='width',
            field=models.PositiveSmallIntegerField(default=288),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(height_field='height', upload_to='photos/%Y/%m/%d/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 2, 12, 28, 298086)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 6, 12, 28, 298099)),
        ),
    ]
