# Generated by Django 4.1.6 on 2023-02-11 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 3, 49, 2, 955263)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 49, 2, 955284)),
        ),
    ]
