# Generated by Django 4.1.6 on 2023-02-10 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_height_remove_category_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 2, 29, 37, 979762)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 6, 29, 37, 979782)),
        ),
    ]
