# Generated by Django 4.1.6 on 2023-02-11 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_packing_date_alter_product_sell_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 3, 49, 22, 521251)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 7, 49, 22, 521274)),
        ),
    ]
