# Generated by Django 4.1.6 on 2023-02-11 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 5, 28, 38, 380563)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 9, 28, 38, 380583)),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
