# Generated by Django 4.1.6 on 2023-02-10 13:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_packing_date_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_temperature',
            field=models.SmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_temperature',
            field=models.SmallIntegerField(default=-5),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 9, 14, 49, 336784)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=20, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.PositiveSmallIntegerField(default=120, help_text='per_100_grams', validators=[django.core.validators.MaxValueValidator(limit_value=999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 13, 14, 49, 336797)),
        ),
    ]
