# Generated by Django 4.1.6 on 2023-02-10 13:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_amount_alter_product_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 9, 20, 22, 601410)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 13, 20, 22, 601423)),
        ),
    ]
