# Generated by Django 4.1.6 on 2023-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_new_price_orderitem_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='new_price',
            new_name='discount_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='old_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
