# Generated by Django 4.1.6 on 2023-02-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_id_alter_category_name_alter_category_slug_and_more'),
        ('orders', '0007_rename_new_price_orderitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product'),
        ),
    ]
