# Generated by Django 4.1.6 on 2023-03-07 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('L', 'L'), ('mL', 'mL')], default='Kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.producer'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='packing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 6, 33, 42, 606958)),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_batches', to='store.product'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='sell_before',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 10, 33, 42, 606977)),
        ),
    ]
